### PR TITLE
SVCPLAN-5555: Add support for SUSE

### PR DESCRIPTION
**Pull request by billglick**
This is being tested on `control-test-opensuse155a`.

### CODE REVIEW

**Comment by billglick** [comment]
PDK and dependencies of this module are way out of date. I'm not sure if it is really worth the effort right now to get this module working with pdk-validate. I spent about 1 hour on this and finally gave up.

**Comment by jakerundall** [comment]
This looks good so far. I can take another look when it's moved out of draft.

**Comment by billglick** [comment]
Last round of changes: 
- combined `pam::redhat` & `pam::suse` into new `pam::authselect` class.

**Review by jakerundall — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
